Repository XtensibleBinaryFormat/XBF, pull requests merged in 2023-06, with the labels that each got.

#8 Add CI for Rust
  .github/workflows/rust.yml
  xdl_rs/src/lib.rs
  xdl_rs/src/xdl_vec/mod.rs
  xdl_rs/src/xdl_vec/vec.rs
Labels: enhancement

#14 Merge in string utility functions
  xdl_rs/src/conversions/base_type.rs
  xdl_rs/src/conversions/primitive.rs
  xdl_rs/src/lib.rs
  xdl_rs/src/util.rs
  xdl_rs/src/xdl_primitive/primitive.rs
  xdl_rs/src/xdl_struct.rs
  xdl_rs/src/xdl_vec/vec_metadata.rs
Labels: enhancement

#19 Add nightly checks (including Miri)
  .github/workflows/rust.yml
Labels: enhancement

#16 Add Bytes type and Struct format to the spec
  docs/specification.md
Labels: documentation

#21 Make Nightly/Miri tests required, add additional hygiene support
  .github/workflows/rust.yml
  README.md
Labels: enhancement

#24 Rename XDL to XBF
  .github/workflows/rust.yml
  docs/background.md
  docs/specification.md
  xbf_rs/.gitignore
  xbf_rs/Cargo.toml
  xbf_rs/src/conversions/base_type.rs
  xbf_rs/src/conversions/mod.rs
  xbf_rs/src/conversions/primitive.rs
  xbf_rs/src/conversions/vec.rs
  xbf_rs/src/lib.rs
  xbf_rs/src/util.rs
  xbf_rs/src/xbf_primitive/mod.rs
  xbf_rs/src/xbf_primitive/primitive.rs
  xbf_rs/src/xbf_primitive/primitive_metadata.rs
  xbf_rs/src/xbf_primitive/primitive_test.rs
  xbf_rs/src/xbf_struct.rs
  xbf_rs/src/xbf_vec/mod.rs
  xbf_rs/src/xbf_vec/vec.rs
  xbf_rs/src/xbf_vec/vec_metadata.rs
Labels: documentation, help wanted

#26 Make XDL to XBF changes in source code
  xbf_rs/Cargo.toml
  xbf_rs/src/conversions/base_type.rs
  xbf_rs/src/conversions/primitive.rs
  xbf_rs/src/conversions/vec.rs
  xbf_rs/src/lib.rs
  xbf_rs/src/xbf_primitive/primitive.rs
  xbf_rs/src/xbf_primitive/primitive_metadata.rs
  xbf_rs/src/xbf_primitive/primitive_test.rs
  xbf_rs/src/xbf_struct.rs
  xbf_rs/src/xbf_vec/vec.rs
  xbf_rs/src/xbf_vec/vec_metadata.rs
Labels: enhancement, help wanted

#18 Add 256 bit number on the wire support
  xbf_rs/src/conversions/primitive.rs
  xbf_rs/src/xbf_primitive/primitive.rs
  xbf_rs/src/xbf_primitive/primitive_test.rs
Labels: enhancement

#27 Change occurences of XDL to XBF in documentation
  COPYRIGHT.md
  LICENSE-APACHE
  LICENSE-MIT
  README.md
Labels: documentation

#22 Trait cleanup
  xbf_rs/src/conversions/vec.rs
  xbf_rs/src/lib.rs
  xbf_rs/src/xbf_primitive/primitive.rs
  xbf_rs/src/xbf_primitive/primitive_metadata.rs
  xbf_rs/src/xbf_primitive/primitive_test.rs
  xbf_rs/src/xbf_struct/struct_metadata.rs
  xbf_rs/src/xbf_vec/vec.rs
  xbf_rs/src/xbf_vec/vec_metadata.rs
Labels: enhancement

#28 Conversions reorg
  xbf_rs/src/base_metadata.rs
  xbf_rs/src/base_type.rs
  xbf_rs/src/conversions/base_type.rs
  xbf_rs/src/conversions/mod.rs
  xbf_rs/src/conversions/primitive.rs
  xbf_rs/src/conversions/vec.rs
  xbf_rs/src/lib.rs
  xbf_rs/src/xbf_primitive/mod.rs
  xbf_rs/src/xbf_primitive/primitive.rs
  xbf_rs/src/xbf_primitive/primitive_metadata.rs
  xbf_rs/src/xbf_primitive/primitive_test.rs
  xbf_rs/src/xbf_struct/struct_metadata.rs
  xbf_rs/src/xbf_struct/struct_type.rs
  xbf_rs/src/xbf_vec/vec.rs
  xbf_rs/src/xbf_vec/vec_metadata.rs
Labels: enhancement

#23 Add scheduled checks, job dependencies
  .github/workflows/rust.yml
Labels: enhancement

#36 Move to more modern rust modules layout
  xbf_rs/src/xbf_primitive.rs
  xbf_rs/src/xbf_struct.rs
  xbf_rs/src/xbf_vec.rs
Labels: enhancement

#30 Feature/bytes
  xbf_rs/src/util.rs
  xbf_rs/src/xbf_primitive/primitive.rs
  xbf_rs/src/xbf_primitive/primitive_metadata.rs
Labels: enhancement
